### ISSUE TITLE
Check every time on start if signed jar file has changed

### ISSUE THREAD

**Issue by jimmyMaci** [astrapi69/mystic-crypt-ui#11]
When the application starts a validation of the application jar file have to be done, for prevent if someone has changed it.

@see [how-to-verify-a-jar-signed-with-jarsigner-programmatically](https://stackoverflow.com/questions/1374170/how-to-verify-a-jar-signed-with-jarsigner-programmatically)
[jar docs](https://docs.oracle.com/javase/6/docs/technotes/guides/jar/jar.html)

**Comment by astrapi69** [comment]
I added a signing of the deployed jar file when the izpack build is made. So everything is done with gradle task.
Is now implemented in develop branch
